erDiagram
  Account ||--o{ Auth
  CropDefinition ||--o{ CropProduct
  ItemDefinition ||--o{ CropProduct
  DropTableDefinition ||--o{ DropTableDetail
  ItemDefinition ||--o{ DropTableDetail
  MapDefinition ||--o{ EditableArea
  DropTableDefinition ||--o{ EntityDefinition
  EntityDefinition ||--o{ EntityStat
  StatDefinition ||--o{ EntityStat
  CropDefinition ||--o{ FarmPlotAllowedCrop
  FarmPlotDefinition ||--o{ FarmPlotAllowedCrop
  FarmPlotDefinition ||--o{ FarmPlotAllowedFertilizer
  MapDefinition ||--o{ FarmPlotDefinition
  FishDefinition ||--o{ FishAllowedBait
  FishDefinition ||--o{ FishHabitat
  FishingSpotDefinition ||--o{ FishHabitat
  FishDefinition ||--o{ FishingDropDefinition
  ItemDefinition ||--o{ FishingDropDefinition
  MapDefinition ||--o{ FishingSpotDefinition
  ItemInstance ||--o{ ItemAcquisitionLog
  ItemDefinition ||--o{ ItemEffectDefinition
  ItemInstance ||--o{ ItemEnhancement
  ItemInstance ||--o{ ItemEnhancementLog
  ItemInstance ||--o{ ItemOption
  ItemInstance ||--o{ ItemRune
  RuneDefinition ||--o{ ItemRune
  ItemDefinition ||--o{ LivestockAllowedFeed
  LivestockDefinition ||--o{ LivestockAllowedFeed
  ItemDefinition ||--o{ LivestockProduct
  LivestockDefinition ||--o{ LivestockProduct
  MapDefinition ||--o{ LogDefinition
  MapDefinition ||--o{ MapDefinition
  MapDefinition ||--o{ MapDynamicObjectState
  MapDefinition ||--o{ MapEnvironment
  MapDefinition ||--o{ MapEvent
  MapDefinition ||--o{ MapLayer
  EntityDefinition ||--o{ MapObject
  MapDefinition ||--o{ MapObject
  MapDefinition ||--o{ MapPlayerState
  MapDefinition ||--o{ MapPortal
  EntityDefinition ||--o{ MapSpawnPoint
  MapDefinition ||--o{ MapSpawnPoint
  MapLayer ||--o{ MapTile
  MapDefinition ||--o{ MapZone
  MapEnvironment ||--o{ MapZone
  MonsterAiBtDefinition ||--o{ MonsterDefinition
  MonsterAiFsmDefinition ||--o{ MonsterDefinition
  MapDefinition ||--o{ MonsterKillLog
  MonsterDefinition ||--o{ MonsterKillLog
  MonsterDefinition ||--o{ MonsterStat
  StatDefinition ||--o{ MonsterStat
  MapDefinition ||--o{ OreDefinition
  Account ||--o{ Player
  AchievementDefinition ||--o{ PlayerAchievement
  Player ||--o{ PlayerAchievement
  ItemDefinition ||--o{ PlayerCraftingLog
  Player ||--o{ PlayerCraftingLog
  RecipeDefinition ||--o{ PlayerCraftingLog
  CropDefinition ||--o{ PlayerCropInstance
  Player ||--o{ PlayerCropInstance
  PlayerFarmPlot ||--o{ PlayerCropInstance
  CropProduct ||--o{ PlayerCropProduct
  ItemDefinition ||--o{ PlayerCropProduct
  PlayerCropInstance ||--o{ PlayerCropProduct
  MapDefinition ||--o{ PlayerFishingLog
  FishDefinition ||--o{ PlayerFishingRecord
  FishingSpotDefinition ||--o{ PlayerFishingRecord
  ItemDefinition ||--o{ PlayerFishingRecord
  Player ||--o{ PlayerFishingRecord
  Player ||--o{ PlayerLevel
  LivestockDefinition ||--o{ PlayerLivestockFeedLog
  Player ||--o{ PlayerLivestockFeedLog
  LivestockDefinition ||--o{ PlayerLivestockInstance
  Player ||--o{ PlayerLivestockInstance
  PlayerLivestockInstance ||--o{ PlayerLivestockProduct
  ItemDefinition ||--o{ PlayerLoggingRecord
  LogDefinition ||--o{ PlayerLoggingRecord
  Party ||--o{ PlayerLoggingRecord
  Player ||--o{ PlayerLoggingRecord
  ResourceNodeDefinition ||--o{ PlayerLoggingRecord
  ItemDefinition ||--o{ PlayerMiningRecord
  OreDefinition ||--o{ PlayerMiningRecord
  Party ||--o{ PlayerMiningRecord
  Player ||--o{ PlayerMiningRecord
  ResourceNodeDefinition ||--o{ PlayerMiningRecord
  MonsterDefinition ||--o{ PlayerMonsterKill
  Player ||--o{ PlayerMonsterKill
  Player ||--o{ PlayerPlot
  PlotDefinition ||--o{ PlayerPlot
  Player ||--o{ PlayerRecipe
  RecipeDefinition ||--o{ PlayerRecipe
  SkillDefinition ||--o{ PlayerSkillLog
  Player ||--o{ PlayerStat
  StatDefinition ||--o{ PlayerStat
  StatDefinition ||--o{ PlayerStatLog
  CraftingStationDefinition ||--o{ RecipeDefinition
  ItemDefinition ||--o{ RecipeDefinition
  ItemDefinition ||--o{ RecipeResult
  RecipeDefinition ||--o{ RecipeResult
  Player ||--o{ ResourceNodeState
  ResourceNodeDefinition ||--o{ ResourceNodeState
  CropDefinition ||--o{ SeedGradeToCropGradeMap
  ItemDefinition ||--o{ SeedGradeToCropGradeMap
  MapZone ||--o{ ZoneEvent
  ChannelDefinition ||--o{ ChatLog
  GuildDefinition ||--o{ ChatLog
  PartyDefinition ||--o{ ChatLog
  Player ||--o{ ChatLog
  ClassDefinition ||--o{ ClassDefinition
  ClassDefinition ||--o{ ClassEquipmentRestriction
  ClassDefinition ||--o{ ClassPassiveSkillDefinition
  SkillDefinition ||--o{ ClassPassiveSkillDefinition
  ClassDefinition ||--o{ ClassTraitDefinition
  ClassDefinition ||--o{ ClassTree
  ChatLog ||--o{ CommunityReportLog
  Player ||--o{ CommunityReportLog
  CookingRecipeDefinition ||--o{ CookingGradeRewardDefinition
  ItemDefinition ||--o{ CookingGradeRewardDefinition
  CookingStationDefinition ||--o{ CookingRecipeDefinition
  ItemDefinition ||--o{ CookingRecipeDefinition
  CookingRecipeDefinition ||--o{ CookingResultDefinition
  ItemDefinition ||--o{ CookingResultDefinition
  CookingRecipeDefinition ||--o{ CookingStepDefinition
  Player ||--o{ FriendRelation
  Player ||--o{ GuildDefinition
  GuildDefinition ||--o{ GuildJoinRequest
  Player ||--o{ GuildJoinRequest
  GuildDefinition ||--o{ GuildMember
  GuildRole ||--o{ GuildMember
  Player ||--o{ GuildMember
  GuildDefinition ||--o{ GuildNotice
  GuildDefinition ||--o{ GuildRole
  ItemDefinition ||--o{ JobLevelDefinition
  JobDefinition ||--o{ JobLevelDefinition
  JobDefinition ||--o{ JobSkillDefinition
  JobSkillDefinition ||--o{ JobSkillDefinition
  ItemDefinition ||--o{ JobSkillLevelDefinition
  JobSkillDefinition ||--o{ JobSkillLevelDefinition
  JobDefinition ||--o{ JobTree
  ItemDefinition ||--o{ MiniGameRewardDefinition
  MiniGameDefinition ||--o{ MiniGameRewardDefinition
  ChatLog ||--o{ ModerationActionLog
  Player ||--o{ ModerationActionLog
  Player ||--o{ PartyDefinition
  PartyDefinition ||--o{ PartyMember
  Player ||--o{ PartyMember
  ClassDefinition ||--o{ PlayerClass
  Player ||--o{ PlayerClass
  ClassDefinition ||--o{ PlayerClassChangeLog
  Player ||--o{ PlayerClassChangeLog
  JobDefinition ||--o{ PlayerJobSkill
  JobSkillDefinition ||--o{ PlayerJobSkill
  Player ||--o{ PlayerJobSkill
  JobDefinition ||--o{ PlayerJobSkillPoint
  Player ||--o{ PlayerJobSkillPoint
  ItemDefinition ||--o{ PlayerMiniGameResult
  MiniGameDefinition ||--o{ PlayerMiniGameResult
  Player ||--o{ PlayerMiniGameResult
  ItemInstance ||--o{ PlayerQuickSlot
  Player ||--o{ PlayerQuickSlot
  PlayerQuickSlotPreset ||--o{ PlayerQuickSlot
  SkillDefinition ||--o{ PlayerQuickSlot
  Player ||--o{ PlayerQuickSlotPreset
  Player ||--o{ PlayerSkill
  SkillDefinition ||--o{ PlayerSkill
  Player ||--o{ PlayerSkillChangeLog
  SkillDefinition ||--o{ PlayerSkillChangeLog
  CookingRecipeDefinition ||--o{ RecipeIngredient
  ItemDefinition ||--o{ RecipeIngredient
  SkillDefinition ||--o{ SkillEffectDefinition
  Player ||--o{ Container
  EventDefinition ||--o{ EventReward
  MailAttachment ||--o{ EventReward
  GuildDefinition ||--o{ GuildTitle
  TitleDefinition ||--o{ GuildTitle
  Container ||--o{ ItemInstance
  ItemDefinition ||--o{ ItemInstance
  MapDefinition ||--o{ LandPlot
  ItemDefinition ||--o{ MailAttachment
  Mail ||--o{ MailAttachment
  Mail ||--o{ MailDeleteLog
  Mail ||--o{ MailReadLog
  Player ||--o{ Notification
  NotificationSchedule ||--o{ NotificationLog
  PetDefinition ||--o{ PetDefinition
  PetDefinition ||--o{ PetSkill
  SkillDefinition ||--o{ PetSkill
  PlayerPet ||--o{ PetStat
  StatDefinition ||--o{ PetStat
  BuffDefinition ||--o{ PlayerBuff
  Player ||--o{ PlayerBuff
  BuffDefinition ||--o{ PlayerBuffLog
  Player ||--o{ PlayerBuffLog
  EventDefinition ||--o{ PlayerEventProgress
  Player ||--o{ PlayerEventProgress
  EventReward ||--o{ PlayerEventRewardLog
  Player ||--o{ PlayerEventRewardLog
  LandPlot ||--o{ PlayerLand
  Player ||--o{ PlayerLand
  NotificationLog ||--o{ PlayerNotificationLog
  Player ||--o{ PlayerNotificationLog
  PetDefinition ||--o{ PlayerPet
  Player ||--o{ PlayerPet
  PetSkill ||--o{ PlayerPetSkill
  PlayerPet ||--o{ PlayerPetSkill
  Player ||--o{ PlayerSeasonPass
  SeasonPassDefinition ||--o{ PlayerSeasonPass
  PlayerSeasonPass ||--o{ PlayerSeasonPassMission
  SeasonPassMission ||--o{ PlayerSeasonPassMission
  Player ||--o{ PlayerSeasonPassRewardLog
  SeasonPassReward ||--o{ PlayerSeasonPassRewardLog
  Player ||--o{ PlayerTitle
  TitleDefinition ||--o{ PlayerTitle
  Player ||--o{ PlayerTitleSlot
  PlayerTitle ||--o{ PlayerTitleSlot
  Player ||--o{ Recommendation
  Player ||--o{ RecommendationLog
  Recommendation ||--o{ RecommendationLog
  SeasonPassDefinition ||--o{ SeasonPassMission
  Player ||--o{ SeasonPassMissionLog
  SeasonPassDefinition ||--o{ SeasonPassMissionLog
  SeasonPassMission ||--o{ SeasonPassMissionLog
  Player ||--o{ SeasonPassPurchaseLog
  SeasonPassDefinition ||--o{ SeasonPassPurchaseLog
  MailAttachment ||--o{ SeasonPassReward
  SeasonPassDefinition ||--o{ SeasonPassReward
  Player ||--o{ SeasonPassRewardActionLog
  SeasonPassDefinition ||--o{ SeasonPassRewardActionLog
  SeasonPassReward ||--o{ SeasonPassRewardActionLog
  BuffDefinition ||--o{ SkillGrantedBuff
  SkillDefinition ||--o{ SkillGrantedBuff
  TitleCategory ||--o{ TitleCategoryMapping
  TitleDefinition ||--o{ TitleCategoryMapping
  TitleDefinition ||--o{ TitleEffect
  TitleDefinition ||--o{ TitleUnlockCondition
  Player ||--o{ TitleUnlockHistory
  TitleDefinition ||--o{ TitleUnlockHistory
  Player ||--o{ BuildingActionLog
  PlayerBuilding ||--o{ BuildingActionLog
  BuildingDefinition ||--o{ BuildingUpgradeDefinition
  BuildingUpgradeDefinition ||--o{ BuildingUpgradeEffect
  BuildingUpgradeDefinition ||--o{ BuildingUpgradeRequiredCurrency
  BuildingUpgradeDefinition ||--o{ BuildingUpgradeRequiredItem
  ItemDefinition ||--o{ BuildingUpgradeRequiredItem
  CurrencyDefinition ||--o{ CurrencyTransactionLog
  Player ||--o{ CurrencyTransactionLog
  CurrencyDefinition ||--o{ MarketListing
  ItemDefinition ||--o{ MarketListing
  ItemInstance ||--o{ MarketListing
  Player ||--o{ MarketListing
  CurrencyDefinition ||--o{ MarketTransaction
  ItemDefinition ||--o{ MarketTransaction
  ItemInstance ||--o{ MarketTransaction
  MarketListing ||--o{ MarketTransaction
  Player ||--o{ MarketTransaction
  BuildingDefinition ||--o{ PlayerBuilding
  Player ||--o{ PlayerBuilding
  PlayerLand ||--o{ PlayerBuilding
  ItemDefinition ||--o{ PlayerInventoryItem
  Player ||--o{ PlayerInventoryItem
  Player ||--o{ PlayerInventoryTabLimit
  CurrencyDefinition ||--o{ Trade
  Player ||--o{ Trade
  ItemDefinition ||--o{ TradeItem
  ItemInstance ||--o{ TradeItem
  Trade ||--o{ TradeItem
  ItemDefinition ||--o{ PlayerEquipmentSlot
  PlayerBuilding ||--o{ PlayerEquipmentSlot
  CropDefinition ||--o{ PlayerGreenhouseCropSlot
  PlayerBuilding ||--o{ PlayerGreenhouseCropSlot
  LivestockDefinition ||--o{ PlayerRanchAnimalSlot
  PlayerBuilding ||--o{ PlayerRanchAnimalSlot
  PlayerBuilding ||--o{ PlayerResearchLabSlot
  ResearchDefinition ||--o{ PlayerResearchLabSlot
  ItemDefinition ||--o{ PlayerStorageSlot
  PlayerBuilding ||--o{ PlayerStorageSlot
    BoardGameRoom ||--o{ BoardGameParticipant
  Player ||--o{ BoardGameParticipant
  BoardGameDefinition ||--o{ BoardGameRoom
  BoardGameRoom ||--o{ BoardGameTurnLog
  Player ||--o{ BoardGameTurnLog
  MapDefinition ||--o{ DungeonDefinition
  MapZone ||--o{ DungeonDefinition
  DungeonDefinition ||--o{ DungeonRun
  MapZone ||--o{ DungeonRun
  Party ||--o{ DungeonRun
  Player ||--o{ DungeonRun
  DungeonRun ||--o{ DungeonRunParticipant
  Player ||--o{ DungeonRunParticipant
  DungeonDefinition ||--o{ DungeonZone
  MapZone ||--o{ DungeonZone
  ShopDefinition ||--o{ NpcDefinition
  NpcDefinition ||--o{ NpcDialogue
  MapDefinition ||--o{ NpcInstance
  MapZone ||--o{ NpcInstance
  NpcDefinition ||--o{ NpcInstance
  NpcDefinition ||--o{ PlayerNpcFavor
  Player ||--o{ PlayerNpcFavor
  MapDefinition ||--o{ Portal
  MapZone ||--o{ Portal
  MapDefinition ||--o{ PortalUseLog
  MapZone ||--o{ PortalUseLog
  Player ||--o{ PortalUseLog
  Portal ||--o{ PortalUseLog
  ItemDefinition ||--o{ ShopItemDefinition
  ShopDefinition ||--o{ ShopItemDefinition
  ItemDefinition ||--o{ ShopTransactionLog
  Player ||--o{ ShopTransactionLog
  ShopDefinition ||--o{ ShopTransactionLog
  Player ||--o{ UserPattern
  Player ||--o{ UserPatternBoardPost
  UserPattern ||--o{ UserPatternBoardPost
  UserPatternBoard ||--o{ UserPatternBoardPost
  Player ||--o{ UserPatternBoardPostComment
  UserPatternBoardPost ||--o{ UserPatternBoardPostComment
  Player ||--o{ UserPatternComment
  UserPattern ||--o{ UserPatternComment
  Player ||--o{ UserPatternFavorite
  UserPattern ||--o{ UserPatternFavorite
  Player ||--o{ UserPatternLike
  UserPattern ||--o{ UserPatternLike
  Player ||--o{ UserPatternReport
  UserPattern ||--o{ UserPatternReport
  Player ||--o{ UserRoom
  Player ||--o{ UserRoomChat
  UserRoom ||--o{ UserRoomChat
  Player ||--o{ UserRoomFavorite
  UserRoom ||--o{ UserRoomFavorite
  Player ||--o{ UserRoomParticipant
  UserRoom ||--o{ UserRoomParticipant
  Player ||--o{ UserRoomReport
  UserRoom ||--o{ UserRoomReport
  Account ||--o{ GMAccount
  GMRole ||--o{ GMAccount
  GMAccount ||--o{ GMActionLog
  GMAccount ||--o{ GMNotice
  Player ||--o{ PlayerBan
  Player ||--o{ PlayerEventParticipation
  WorldEvent ||--o{ PlayerEventParticipation
  Player ||--o{ SecurityIncidentLog
  DialogueDefinition ||--o{ DialogueLink
  ShopDefinition ||--o{ NpcDefinition
  MapDefinition ||--o{ NpcInstance
  MapZone ||--o{ NpcInstance
  NpcDefinition ||--o{ NpcInstance
  NpcDefinition ||--o{ PlayerNpcFavor
  Player ||--o{ PlayerNpcFavor
  ItemDefinition ||--o{ ShopItemDefinition
  ShopDefinition ||--o{ ShopItemDefinition
  ItemDefinition ||--o{ ShopTransactionLog
  Player ||--o{ ShopTransactionLog
  ShopDefinition ||--o{ ShopTransactionLog