import os

def generate_dependency_injection(entities, output_dir):
    """
    entities: List[str] - 엔티티 이름(파스칼케이스)
    output_dir: str - 생성할 루트 경로(예: 'test/Infrastructure')
    """
    lines = [
        "// THIS FILE IS AUTO-GENERATED BY codegen. DO NOT EDIT MANUALLY!",
        "using Microsoft.Extensions.DependencyInjection;",
        "using Server.Core.Repositories;",
        "using Server.Infrastructure.Repositories;",
        "",
        "namespace Server.Infrastructure;",
        "",
        "public static class DependencyInjection",
        "{",
        "    public static void AddRepositories(this IServiceCollection services)",
        "    {",
    ]
    from codegen.util import safe_pascal_case
    seen = set()
    for entity in entities:
        entity_fixed = safe_pascal_case(entity)
        if entity_fixed not in seen:
            lines.append(f"        services.AddScoped<I{entity_fixed}Repository, {entity_fixed}Repository>();")
            seen.add(entity_fixed)
    lines += [
        "    }",
        "}"
    ]
    code = "\n".join(lines)
    out_path = os.path.normpath(os.path.join(output_dir, "DependencyInjection.cs"))
    os.makedirs(os.path.dirname(out_path), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(code)
