// THIS FILE IS AUTO-GENERATED BY codegen. DO NOT EDIT MANUALLY!
using Microsoft.Extensions.DependencyInjection;
using Server.Core.Repositories;
using Server.Infrastructure.Repositories;

namespace Server.Infrastructure;

public static class DependencyInjection
{
    public static void AddRepositories(this IServiceCollection services)
    {
        services.AddScoped<IAccountRepository, AccountRepository>();
        services.AddScoped<IAchievementCategoryRepository, AchievementCategoryRepository>();
        services.AddScoped<IAchievementDefinitionRepository, AchievementDefinitionRepository>();
        services.AddScoped<IBoardGameDefinitionRepository, BoardGameDefinitionRepository>();
        services.AddScoped<IBuffDefinitionRepository, BuffDefinitionRepository>();
        services.AddScoped<IBuildingDefinitionRepository, BuildingDefinitionRepository>();
        services.AddScoped<IBuildingUpgradeDefinitionRepository, BuildingUpgradeDefinitionRepository>();
        services.AddScoped<ICategoryRankingRepository, CategoryRankingRepository>();
        services.AddScoped<IChannelDefinitionRepository, ChannelDefinitionRepository>();
        services.AddScoped<IClassDefinitionRepository, ClassDefinitionRepository>();
        services.AddScoped<IClassSkillDefinitionRepository, ClassSkillDefinitionRepository>();
        services.AddScoped<IClassTraitDefinitionRepository, ClassTraitDefinitionRepository>();
        services.AddScoped<IContainerRepository, ContainerRepository>();
        services.AddScoped<ICookingGradeRewardDefinitionRepository, CookingGradeRewardDefinitionRepository>();
        services.AddScoped<ICookingRecipeDefinitionRepository, CookingRecipeDefinitionRepository>();
        services.AddScoped<ICookingResultDefinitionRepository, CookingResultDefinitionRepository>();
        services.AddScoped<ICookingStepDefinitionRepository, CookingStepDefinitionRepository>();
        services.AddScoped<ICropDefinitionRepository, CropDefinitionRepository>();
        services.AddScoped<ICurrencyDefinitionRepository, CurrencyDefinitionRepository>();
        services.AddScoped<IDialogueDefinitionRepository, DialogueDefinitionRepository>();
        services.AddScoped<IDropTableDefinitionRepository, DropTableDefinitionRepository>();
        services.AddScoped<IDungeonDefinitionRepository, DungeonDefinitionRepository>();
        services.AddScoped<IEntityDefinitionRepository, EntityDefinitionRepository>();
        services.AddScoped<IEventDefinitionRepository, EventDefinitionRepository>();
        services.AddScoped<IFarmPlotDefinitionRepository, FarmPlotDefinitionRepository>();
        services.AddScoped<IFishDefinitionRepository, FishDefinitionRepository>();
        services.AddScoped<IFishingSpotDefinitionRepository, FishingSpotDefinitionRepository>();
        services.AddScoped<IGmRoleRepository, GmRoleRepository>();
        services.AddScoped<IGuildDefinitionRepository, GuildDefinitionRepository>();
        services.AddScoped<IGuildLevelDefinitionRepository, GuildLevelDefinitionRepository>();
        services.AddScoped<IItemDefinitionRepository, ItemDefinitionRepository>();
        services.AddScoped<IItemEffectDefinitionRepository, ItemEffectDefinitionRepository>();
        services.AddScoped<IJobDefinitionRepository, JobDefinitionRepository>();
        services.AddScoped<IJobLevelDefinitionRepository, JobLevelDefinitionRepository>();
        services.AddScoped<IJobSkillDefinitionRepository, JobSkillDefinitionRepository>();
        services.AddScoped<IJobSkillLevelDefinitionRepository, JobSkillLevelDefinitionRepository>();
        services.AddScoped<ILevelDefinitionRepository, LevelDefinitionRepository>();
        services.AddScoped<ILivestockDefinitionRepository, LivestockDefinitionRepository>();
        services.AddScoped<ILogDefinitionRepository, LogDefinitionRepository>();
        services.AddScoped<IMailRepository, MailRepository>();
        services.AddScoped<IMapDefinitionRepository, MapDefinitionRepository>();
        services.AddScoped<IMiniGameDefinitionRepository, MiniGameDefinitionRepository>();
        services.AddScoped<IMiniGameRewardDefinitionRepository, MiniGameRewardDefinitionRepository>();
        services.AddScoped<IMonsterAiBtDefinitionRepository, MonsterAiBtDefinitionRepository>();
        services.AddScoped<IMonsterAiFsmDefinitionRepository, MonsterAiFsmDefinitionRepository>();
        services.AddScoped<IMonsterDefinitionRepository, MonsterDefinitionRepository>();
        services.AddScoped<INotificationScheduleRepository, NotificationScheduleRepository>();
        services.AddScoped<INpcDefinitionRepository, NpcDefinitionRepository>();
        services.AddScoped<IOreDefinitionRepository, OreDefinitionRepository>();
        services.AddScoped<IPartyDefinitionRepository, PartyDefinitionRepository>();
        services.AddScoped<IPetDefinitionRepository, PetDefinitionRepository>();
        services.AddScoped<IPlayerRepository, PlayerRepository>();
        services.AddScoped<IQuestDefinitionRepository, QuestDefinitionRepository>();
        services.AddScoped<IQuestGroupRepository, QuestGroupRepository>();
        services.AddScoped<IRecipeDefinitionRepository, RecipeDefinitionRepository>();
        services.AddScoped<ISeasonPassDefinitionRepository, SeasonPassDefinitionRepository>();
        services.AddScoped<IShopDefinitionRepository, ShopDefinitionRepository>();
        services.AddScoped<IShopItemDefinitionRepository, ShopItemDefinitionRepository>();
        services.AddScoped<ISkillDefinitionRepository, SkillDefinitionRepository>();
        services.AddScoped<ISkillEffectDefinitionRepository, SkillEffectDefinitionRepository>();
        services.AddScoped<IStatDefinitionRepository, StatDefinitionRepository>();
        services.AddScoped<ITagRepository, TagRepository>();
        services.AddScoped<ITitleCategoryRepository, TitleCategoryRepository>();
        services.AddScoped<ITitleDefinitionRepository, TitleDefinitionRepository>();
        services.AddScoped<IUserPatternBoardRepository, UserPatternBoardRepository>();
    }
}